admin: 1139602557

start_balance: 1000
loan_value: 500

games:
  blackjack:
    min_players: 1 
    max_players: 6 # Without dealer

localization:
  admin:
    chat_admitted: Чат одобрен для использования
    chat_denied: Чат попущен
    insufficient_reply: Ответьте командой на сообщение пользователя
    set_balance_successful: Баланс пользователя изменен
    set_debt_successful: Долг пользователя изменен

  dep:
    slot:
      deposit_required: |-
        Сначала сделайте ставку.
        /dep [ставка]
        /slot [ставка]
      win: |-
        Поздравляю, вы выиграли, ставка x5!
        Выигрыш: {deposit}
      jackpot: |-
        Джекпот! Ваша ставка x10!
        Выигрыш: {deposit}
      loss: |-
        Не повезло, ваш депозит сгорел.
        Попробуйте еще раз, фортуна точно будет на вашей стороне!
    empty_subject: Возвращайся когда у тебя будет что мне предложить
    insufficient_balance: Недостаточно средств, у вас на балансе {balance}
    non_positive_value: 🖕 (с уважением)
    accepted: 'Ваш депозит: {value}'
    invalid_subject: Я такое не принимаю
    loan:
      funds_available: У тебя и так есть деньги, иди отсюда, попрошайка.
      already_received: Я и так занимал тебе сегодня, иди отсюда, лудик несчастный.
      received: Сцедил тебе {loan_value} манесов

  blackjack:
    room:
      make: Создать комнату для игры в блэкджек?
      waiting: |
        Собираем стол в блэкджек! #{room}
        Играют: {players}

  rooms:
    make_btn: Создать
    start_btn: Начать
    exit_btn: Покинуть
    join_btn: Присоединиться ({joined_players}/{max_players})
    successful_joined: "Вы присоединились к комнате #{room}"
    successful_exited: "Вы покинули комнату #{room}"
    closed_due_to_no_players: "Комната #{room} удалена, так как в ней не осталось игроков"
    err_not_joined: Вы не состоите в этой комнате
    err_already_joined: Вы уже присоединились к этой комнате
    err_not_exists: Ошибка! Комнаты не существует
    err_too_many_players: В этой комнате слишком много игроков, присоединиться не получится

  start:
    welcome: |-
      Добро пожаловать в аномальный казик.
      Тебе начислен приветственный бонус: {start_balance}!

  state:
    balance: |-
      Ваш баланс: {balance}
      Текущий депозит: {deposit}
      Ваш долг: {debt}
    stats: |-
      Пролудоманенно: {total_lost}
      Всего выиграно: {total_earned}
      Всего побед: {total_wins}
      Сыграно в слотмашину: {total_slot_play}/{total_slot_wins}

  system:
    critical_error: Произошла критическая ошибка!
    err_too_many_stickers: Вы лудили слишком часто, казик накрыли менты, ставка не возвращается.
    err_message_inaccessible: Ошибка, сообщение недоступно
    err_not_your_button: Эта кнопка предназначена не вам
